### ISSUE TITLE
Collection to Pull Variables from a Collection

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/collections#12]
I'd like to have a collection that will pull a collection from the Postman API, spider all paths and parameters, then output a list of variables used via the visualizer.

**Comment by Gbahdeyboh** [comment]
The collection can be found [here](https://www.postman.com/postman/workspace/aa5fb3b8-0090-4b5e-b3b4-fa5c1f2d080d/request/20781379-030115ce-34c4-42a3-be6b-a93ae3526a57).

![Screenshot 2023-03-07 at 21 10 26](https://user-images.githubusercontent.com/29985200/223541012-ffeb0189-4920-43ef-9c83-0f740eb8df40.png)
